In [71]:
import pandas as pd

In [72]:
df_collisions_uk = pd.read_csv('../data/processed/merged_uk.csv',low_memory=False)

In [73]:
print(len(df_collisions_uk.columns.to_list()))

df_collisions_uk['casualty_severity']

101

0         3
1         3
2         3
3         3
4         3
         ..
100922    3
100923    3
100924    3
100925    3
100926    3
Name: casualty_severity, Length: 100927, dtype: object

In [74]:
df_collisions_uk.columns.to_list()

['collision_index',
 'collision_year',
 'collision_ref_no',
 'location_easting_osgr',
 'location_northing_osgr',
 'longitude',
 'latitude',
 'police_force',
 'collision_severity',
 'number_of_vehicles',
 'number_of_casualties',
 'day_of_week',
 'time',
 'local_authority_district',
 'local_authority_ons_district',
 'local_authority_highway',
 'local_authority_highway_current',
 'first_road_class',
 'first_road_number',
 'road_type',
 'speed_limit',
 'junction_detail_historic',
 'junction_detail',
 'junction_control',
 'second_road_class',
 'second_road_number',
 'pedestrian_crossing_human_control_historic',
 'pedestrian_crossing_physical_facilities_historic',
 'pedestrian_crossing',
 'light_conditions',
 'weather_conditions',
 'road_surface_conditions',
 'special_conditions_at_site',
 'carriageway_hazards_historic',
 'carriageway_hazards',
 'urban_or_rural_area',
 'did_police_officer_attend_scene_of_accident',
 'trunk_road_flag',
 'lsoa_of_accident_location',
 'enhanced_severity_collision',
 'collision_injury_based',
 'collision_adjusted_severity_serious',
 'collision_adjusted_severity_slight',
 'vehicle_reference_1',
 'vehicle_type',
 'towing_and_articulation',
 'vehicle_manoeuvre_historic',
 'vehicle_manoeuvre',
 'vehicle_direction_from',
 'vehicle_direction_to',
 'vehicle_location_restricted_lane_historic',
 'vehicle_location_restricted_lane',
 'junction_location',
 'skidding_and_overturning',
 'hit_object_in_carriageway',
 'vehicle_leaving_carriageway',
 'hit_object_off_carriageway',
 'first_point_of_impact',
 'vehicle_left_hand_drive',
 'journey_purpose_of_driver_historic',
 'journey_purpose_of_driver',
 'sex_of_driver',
 'age_of_driver',
 'age_band_of_driver',
 'engine_capacity_cc',
 'propulsion_code',
 'age_of_vehicle',
 'generic_make_model',
 'driver_imd_decile',
 'lsoa_of_driver',
 'escooter_flag',
 'driver_distance_banding',
 'vehicle_reference_2',
 'casualty_reference',
 'casualty_class',
 'sex_of_casualty',
 'age_of_casualty',
 'age_band_of_casualty',
 'casualty_severity',
 'pedestrian_location',
 'pedestrian_movement',
 'car_passenger',
 'bus_or_coach_passenger',
 'pedestrian_road_maintenance_worker',
 'casualty_type',
 'casualty_imd_decile',
 'lsoa_of_casualty',
 'enhanced_casualty_severity',
 'casualty_injury_based',
 'casualty_adjusted_severity_serious',
 'casualty_adjusted_severity_slight',
 'casualty_distance_banding',
 'is_car',
 'is_cyle',
 'is_mcyle',
 'is_goodsv',
 'is_other',
 'is_pedestrian',
 'year',
 'month',
 'day']

In [75]:
selected_columns = ['collision_index','collision_year',
 'collision_ref_no',
 'location_easting_osgr',
 'location_northing_osgr',
 'longitude',
 'latitude',
 #'police_force',
 'casualty_severity',
 #'number_of_vehicles',
 #'number_of_casualties',
 'day_of_week',
 'time',
 'local_authority_district',
 'local_authority_ons_district',
 #'local_authority_highway',
 #'local_authority_highway_current',
 #'first_road_class',
 #'first_road_number',
 #'road_type',
 #'speed_limit',
 #'junction_detail_historic',
 'junction_detail',
 'junction_control',
 #'second_road_class',
 #'second_road_number',
 #'pedestrian_crossing_human_control_historic',
 #'pedestrian_crossing_physical_facilities_historic',
 #'pedestrian_crossing',
 'light_conditions',
 'weather_conditions',
 'road_surface_conditions',
 #'special_conditions_at_site',
 #'carriageway_hazards_historic',
 #'carriageway_hazards',
 #'urban_or_rural_area',
 #'did_police_officer_attend_scene_of_accident',
 #'trunk_road_flag',
 #'lsoa_of_accident_location',
 #'enhanced_severity_collision',
 #'collision_injury_based',
 #'collision_adjusted_severity_serious',
 #'collision_adjusted_severity_slight',
 #'vehicle_reference_1',
 #'vehicle_type',
 #'towing_and_articulation',
 #'vehicle_manoeuvre_historic',
 'vehicle_manoeuvre',
 'vehicle_direction_from',
 'vehicle_direction_to',
 #'vehicle_location_restricted_lane_historic',
 #'vehicle_location_restricted_lane',
 #'junction_location',
 #'skidding_and_overturning',
 'hit_object_in_carriageway',
 'vehicle_leaving_carriageway',
 'hit_object_off_carriageway',
 #'first_point_of_impact',
 #'vehicle_left_hand_drive',
 #'journey_purpose_of_driver_historic',
 #'journey_purpose_of_driver',
 #'sex_of_driver',
 #'age_of_driver',
 #'age_band_of_driver',
 #'engine_capacity_cc',
 #'propulsion_code',
 #'age_of_vehicle',
 #'generic_make_model',
#  'driver_imd_decile',
#  'lsoa_of_driver',
#  'escooter_flag',
#  'driver_distance_banding',
#  'vehicle_reference_2',
#  'casualty_reference',
#  'casualty_class',
#  'sex_of_casualty',
#  'age_of_casualty',
#  'age_band_of_casualty',
# 'casualty_severity',
#  'pedestrian_location',
#  'pedestrian_movement',
#  'car_passenger',
#  'bus_or_coach_passenger',
#  'pedestrian_road_maintenance_worker',
#  'casualty_type',
#  'casualty_imd_decile',
#  'lsoa_of_casualty',
#  'enhanced_casualty_severity',
#  'casualty_injury_based',
#  'casualty_adjusted_severity_serious',
#  'casualty_adjusted_severity_slight',
#  'casualty_distance_banding',
 'is_car',
 'is_cyle',
 'is_mcyle',
 'is_goodsv',
 'is_other',
 'is_pedestrian',
 #'year',
 'month',
 'day']

In [76]:
df_collisions_uk.columns = ['casualty_severity' if col == 'collision_severity' else col for col in df_collisions_uk.columns]

df_reduced_uk = df_collisions_uk[selected_columns]

df_reduced_uk.to_csv('../data/processed/reduced_uk_dataset.csv', index=False)

df_reduced_uk

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,casualty_severity,casualty_severity,day_of_week,...,vehicle_leaving_carriageway,hit_object_off_carriageway,is_car,is_cyle,is_mcyle,is_goodsv,is_other,is_pedestrian,month,day
0,2024010486807,2024,010486807,527188,184782,-0.16712,51.54761,3,3,2,...,9,99,1,1,0,0,0,0,1,1
1,2024010486821,2024,010486821,528936,194721,-0.13828,51.63653,3,3,2,...,9,99,1,0,0,0,0,0,1,1
2,2024010486824,2024,010486824,552699,185940,0.20103,51.55169,3,3,2,...,0,0,1,0,0,0,0,0,1,1
3,2024010486825,2024,010486825,545623,177185,0.09543,51.47489,3,3,2,...,0,0,1,0,1,0,0,0,1,1
4,2024010486828,2024,010486828,536554,178468,-0.03457,51.48868,3,3,2,...,0,0,0,0,0,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,190198,627793,-5.32322,55.49874,3,3,5,...,0,0,1,0,0,0,0,0,8,15
100923,2024991578058,2024,991578058,343704,732367,-2.91560,56.48003,3,3,6,...,0,0,1,1,0,0,0,0,11,15
100924,2024991579036,2024,991579036,354980,685252,-2.72450,56.05799,3,3,5,...,0,0,1,0,0,0,0,1,11,7
100925,2024991579213,2024,991579213,270691,650765,-4.06082,55.73297,3,3,6,...,"[0, 1]",0,1,0,0,0,0,0,11,15
100926,2024991580347,2024,991580347,326744,692503,-3.17980,56.11963,3,3,3,...,0,0,1,0,0,0,0,0,11,19

In [77]:
df_collisions_uk_with_kind_and_type = pd.read_csv('../data/processed/merged_uk_with_kind_and_type.csv',low_memory=False)

In [78]:
df_collisions_uk_with_kind_and_type.columns.to_list()

['collision_index',
 'collision_year',
 'collision_ref_no',
 'location_easting_osgr',
 'location_northing_osgr',
 'longitude',
 'latitude',
 'police_force',
 'collision_severity',
 'number_of_vehicles',
 'number_of_casualties',
 'day_of_week',
 'time',
 'local_authority_district',
 'local_authority_ons_district',
 'local_authority_highway',
 'local_authority_highway_current',
 'first_road_class',
 'first_road_number',
 'road_type',
 'speed_limit',
 'junction_detail_historic',
 'junction_detail',
 'junction_control',
 'second_road_class',
 'second_road_number',
 'pedestrian_crossing_human_control_historic',
 'pedestrian_crossing_physical_facilities_historic',
 'pedestrian_crossing',
 'light_conditions',
 'weather_conditions',
 'road_surface_conditions',
 'special_conditions_at_site',
 'carriageway_hazards_historic',
 'carriageway_hazards',
 'urban_or_rural_area',
 'did_police_officer_attend_scene_of_accident',
 'trunk_road_flag',
 'lsoa_of_accident_location',
 'enhanced_severity_collision',
 'collision_injury_based',
 'collision_adjusted_severity_serious',
 'collision_adjusted_severity_slight',
 'vehicle_reference_1',
 'vehicle_type',
 'towing_and_articulation',
 'vehicle_manoeuvre_historic',
 'vehicle_manoeuvre',
 'vehicle_direction_from',
 'vehicle_direction_to',
 'vehicle_location_restricted_lane_historic',
 'vehicle_location_restricted_lane',
 'junction_location',
 'skidding_and_overturning',
 'hit_object_in_carriageway',
 'vehicle_leaving_carriageway',
 'hit_object_off_carriageway',
 'first_point_of_impact',
 'vehicle_left_hand_drive',
 'journey_purpose_of_driver_historic',
 'journey_purpose_of_driver',
 'sex_of_driver',
 'age_of_driver',
 'age_band_of_driver',
 'engine_capacity_cc',
 'propulsion_code',
 'age_of_vehicle',
 'generic_make_model',
 'driver_imd_decile',
 'lsoa_of_driver',
 'escooter_flag',
 'driver_distance_banding',
 'vehicle_reference_2',
 'casualty_reference',
 'casualty_class',
 'sex_of_casualty',
 'age_of_casualty',
 'age_band_of_casualty',
 'casualty_severity',
 'pedestrian_location',
 'pedestrian_movement',
 'car_passenger',
 'bus_or_coach_passenger',
 'pedestrian_road_maintenance_worker',
 'casualty_type',
 'casualty_imd_decile',
 'lsoa_of_casualty',
 'enhanced_casualty_severity',
 'casualty_injury_based',
 'casualty_adjusted_severity_serious',
 'casualty_adjusted_severity_slight',
 'casualty_distance_banding',
 'is_car',
 'is_cyle',
 'is_mcyle',
 'is_goodsv',
 'is_other',
 'is_pedestrian',
 'year',
 'month',
 'day',
 'kind_of_accident_1',
 'kind_of_accident_2',
 'kind_of_accident_3',
 'kind_of_accident_5',
 'kind_of_accident_7',
 'kind_of_accident_0',
 'kind_of_accident_8',
 'kind_of_accident_9',
 'kind_of_accident_6',
 'kind_of_accident_4',
 'type_of_accident_1',
 'type_of_accident_2',
 'type_of_accident_3',
 'type_of_accident_4',
 'type_of_accident_5',
 'type_of_accident_6']

In [79]:
df_collisions_uk_with_kind_and_type.columns

Index(['collision_index', 'collision_year', 'collision_ref_no',
       'location_easting_osgr', 'location_northing_osgr', 'longitude',
       'latitude', 'police_force', 'collision_severity', 'number_of_vehicles',
       ...
       'kind_of_accident_8', 'kind_of_accident_9', 'kind_of_accident_6',
       'kind_of_accident_4', 'type_of_accident_1', 'type_of_accident_2',
       'type_of_accident_3', 'type_of_accident_4', 'type_of_accident_5',
       'type_of_accident_6'],
      dtype='object', length=117)

In [80]:
select = ['collision_index',
 'collision_year',
 'collision_ref_no',
 'location_easting_osgr',
 'location_northing_osgr',
 'longitude',
 'latitude',
 #'police_force',
 'casualty_severity',
#  'number_of_vehicles',
#  'number_of_casualties',
 'day_of_week',
 'time',
 'local_authority_district',
#  'local_authority_ons_district',
#  'local_authority_highway',
#  'local_authority_highway_current',
#  'first_road_class',
#  'first_road_number',
#  'road_type',
#  'speed_limit',
#  'junction_detail_historic',
#  'junction_detail',
#  'junction_control',
#  'second_road_class',
#  'second_road_number',
#  'pedestrian_crossing_human_control_historic',
#  'pedestrian_crossing_physical_facilities_historic',
#  'pedestrian_crossing',
 'light_conditions',
 'weather_conditions',
 'road_surface_conditions',
#  'special_conditions_at_site',
#  'carriageway_hazards_historic',
#  'carriageway_hazards',
#  'urban_or_rural_area',
#  'did_police_officer_attend_scene_of_accident',
#  'trunk_road_flag',
#  'lsoa_of_accident_location',
#  'enhanced_severity_collision',
#  'collision_injury_based',
#  'collision_adjusted_severity_serious',
#  'collision_adjusted_severity_slight',
#  'vehicle_reference_1',
#  'vehicle_type',
#  'towing_and_articulation',
#  'vehicle_manoeuvre_historic',
#  'vehicle_manoeuvre',
#  'vehicle_direction_from',
#  'vehicle_direction_to',
#  'vehicle_location_restricted_lane_historic',
#  'vehicle_location_restricted_lane',
#  'junction_location',
#  'skidding_and_overturning',
#  'hit_object_in_carriageway',
#  'vehicle_leaving_carriageway',
#  'hit_object_off_carriageway',
#  'first_point_of_impact',
#  'vehicle_left_hand_drive',
#  'journey_purpose_of_driver_historic',
#  'journey_purpose_of_driver',
#  'sex_of_driver',
#  'age_of_driver',
#  'age_band_of_driver',
#  'engine_capacity_cc',
#  'propulsion_code',
#  'age_of_vehicle',
#  'generic_make_model',
#  'driver_imd_decile',
#  'lsoa_of_driver',
#  'escooter_flag',
#  'driver_distance_banding',
#  'vehicle_reference_2',
#  'casualty_reference',
#  'casualty_class',
#  'sex_of_casualty',
#  'age_of_casualty',
#  'age_band_of_casualty',
#  'casualty_severity',
#  'pedestrian_location',
#  'pedestrian_movement',
#  'car_passenger',
#  'bus_or_coach_passenger',
#  'pedestrian_road_maintenance_worker',
#  'casualty_type',
#  'casualty_imd_decile',
#  'lsoa_of_casualty',
#  'enhanced_casualty_severity',
#  'casualty_injury_based',
#  'casualty_adjusted_severity_serious',
#  'casualty_adjusted_severity_slight',
#  'casualty_distance_banding',
 'is_car',
 'is_cyle',
 'is_mcyle',
 'is_goodsv',
 'is_other',
 'is_pedestrian',
 'year',
 'month',
 'day',
 'kind_of_accident_1',
 'kind_of_accident_2',
 'kind_of_accident_3',
 'kind_of_accident_5',
 'kind_of_accident_7',
 'kind_of_accident_0',
 'kind_of_accident_8',
 'kind_of_accident_9',
 'kind_of_accident_6',
 'kind_of_accident_4',
 'type_of_accident_1',
 'type_of_accident_2',
 'type_of_accident_3',
 'type_of_accident_4',
 'type_of_accident_5',
 'type_of_accident_6']

In [82]:
df_reduced_uk_with_kind_and_type = df_collisions_uk_with_kind_and_type[select]
df_reduced_uk_with_kind_and_type

df_reduced_uk_with_kind_and_type.to_csv('../data/processed/reduced_uk_dataset_with_kind_and_type.csv', index=False)

df_reduced_uk_with_kind_and_type

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,casualty_severity,day_of_week,time,...,kind_of_accident_8,kind_of_accident_9,kind_of_accident_6,kind_of_accident_4,type_of_accident_1,type_of_accident_2,type_of_accident_3,type_of_accident_4,type_of_accident_5,type_of_accident_6
0,2024010486807,2024,010486807,527188,184782,-0.16712,51.54761,3,2,01:00,...,0,0,0,0,1,0,0,0,0,0
1,2024010486821,2024,010486821,528936,194721,-0.13828,51.63653,3,2,01:42,...,0,0,0,0,1,0,0,0,0,0
2,2024010486824,2024,010486824,552699,185940,0.20103,51.55169,3,2,02:23,...,0,0,0,0,1,0,0,0,0,0
3,2024010486825,2024,010486825,545623,177185,0.09543,51.47489,3,2,01:08,...,0,0,0,0,1,0,0,0,0,0
4,2024010486828,2024,010486828,536554,178468,-0.03457,51.48868,3,2,00:35,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,190198,627793,-5.32322,55.49874,3,5,14:25,...,0,0,0,0,1,0,0,0,0,0
100923,2024991578058,2024,991578058,343704,732367,-2.91560,56.48003,3,6,14:10,...,0,0,0,0,1,0,0,0,0,0
100924,2024991579036,2024,991579036,354980,685252,-2.72450,56.05799,3,5,11:00,...,0,0,1,0,0,0,1,1,0,0
100925,2024991579213,2024,991579213,270691,650765,-4.06082,55.73297,3,6,17:44,...,0,1,0,1,1,0,0,0,0,0
100926,2024991580347,2024,991580347,326744,692503,-3.17980,56.11963,3,3,11:41,...,0,0,0,1,1,0,0,0,0,0